[tasks.dev]
run = [
  {tasks=["test","build"]}
]
sources = ["internal/**/*.go", "main.go"]

[tasks.test]
description="Build tuo"
run = "go test ./..."
sources = ["internal/**/*.go", "main.go"]

[tasks.build]
description="Build tuo"
run = "go build -o tuo"
outputs = ["tuo"]
sources = ["internal/**/*.go", "main.go"]

[tasks.log]
description="Tail log"
depends=["build"]
run="tail -f tuo.log"
